let propertyImages=[];let importedImages=[];let agentImage="";
const $=id=>document.getElementById(id);
function val(id){const el=$(id);return el?el.value.trim():""}
function setVal(id,value){const el=$(id);if(el&&value!==undefined&&value!==null&&value!=="")el.value=value}
function setText(selector,text){document.querySelectorAll(selector).forEach(el=>el.textContent=text||"")}
function setStatus(message){const el=$("importStatus");if(el)el.textContent=message||""}
function setBackground(selector,src){const el=document.querySelector(selector);if(!el)return;if(src){el.style.backgroundImage=`url("${src}")`;el.textContent=""}}
function applyListingData(data){setVal("title",data.title);setVal("price",data.price);setVal("location",data.location);setVal("beds",data.beds);setVal("baths",data.baths);setVal("area",data.area);setVal("propertyType",data.propertyType);setVal("description",data.description);if(Array.isArray(data.features)&&data.features.length)setVal("features",data.features.join("\n"));importedImages=Array.isArray(data.imageUrls)?data.imageUrls:[];renderPhotoPreview();buildBrochure()}
async function checkHealth(){try{const r=await fetch(`${window.location.origin}/api/health?v=${Date.now()}`);const d=await r.json();setStatus(`API OK. Version: ${d.version}`)}catch(e){setStatus("API check failed: "+e.message)}}
async function runMockImport(){try{const r=await fetch(`${window.location.origin}/api/mock-import?v=${Date.now()}`);const d=await r.json();applyListingData(d);setStatus("Mock import successful.")}catch(e){setStatus("Mock import failed: "+e.message)}}
async function parseListingText(){const text=val("listingText");if(!text){setStatus("Paste listing text first.");return}try{const r=await fetch(`${window.location.origin}/api/parse-text?v=${Date.now()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Parser failed");applyListingData(d);setStatus("Listing text parsed successfully.")}catch(e){setStatus("Text parser failed: "+e.message)}}
async function importListing(){try{const r=await fetch(`${window.location.origin}/api/import-listing?v=${Date.now()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:val("listingUrl")})});const d=await r.json();if(!r.ok)throw new Error(d.error||"URL import failed");applyListingData(d);setStatus("URL import route connected. Use Paste Listing Text for reliable extraction.")}catch(e){setStatus("URL import failed: "+e.message)}}
function renderPhotoPreview(){const preview=$("photoPreview");if(!preview)return;preview.innerHTML="";[...propertyImages,...importedImages].forEach(src=>{const img=document.createElement("img");img.src=src;preview.appendChild(img)})}
function handlePropertyPhotos(event){propertyImages=[];const files=Array.from(event.target.files||[]);let loaded=0;if(!files.length)return;files.forEach(file=>{const reader=new FileReader();reader.onload=e=>{propertyImages.push(e.target.result);loaded++;if(loaded===files.length){renderPhotoPreview();buildBrochure()}};reader.readAsDataURL(file)})}
function handleAgentPhoto(event){const file=event.target.files&&event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{agentImage=e.target.result;const preview=$("agentPhotoPreview");if(preview){preview.innerHTML="";const img=document.createElement("img");img.src=agentImage;preview.appendChild(img)}buildBrochure()};reader.readAsDataURL(file)}
function buildBrochure(){setText(".outCompany",val("company")||"Betterhomes");setText(".outTitle",val("title")||"Property Title");setText(".outLocation",val("location"));setText(".outPrice",val("price"));setText(".outBeds",val("beds"));setText(".outBaths",val("baths"));setText(".outArea",val("area"));setText(".outType",val("propertyType"));setText(".outDescription",val("description"));setText(".outAgent",val("agent"));setText(".outJobTitle",val("jobTitle"));setText(".outContact",[val("phone"),val("email")].filter(Boolean).join(" · "));const features=val("features").split("\n").map(x=>x.trim()).filter(Boolean).slice(0,12);const ul=document.querySelector(".outFeatures");if(ul){ul.innerHTML="";features.forEach(feature=>{const li=document.createElement("li");li.textContent=feature;ul.appendChild(li)})}const images=[...propertyImages,...importedImages];setBackground("#coverPhoto",images[0]);setBackground(".p1",images[0]);setBackground(".p2",images[1]);setBackground(".p3",images[2]);setBackground(".p4",images[3]);const ap=$("brochureAgentPhoto");if(ap&&agentImage){ap.style.backgroundImage=`url("${agentImage}")`;ap.textContent=""}}
document.addEventListener("DOMContentLoaded",()=>{$("importBtn").addEventListener("click",importListing);$("parseTextBtn").addEventListener("click",parseListingText);$("mockBtn").addEventListener("click",runMockImport);$("healthBtn").addEventListener("click",checkHealth);$("photoInput").addEventListener("change",handlePropertyPhotos);$("agentPhotoInput").addEventListener("change",handleAgentPhoto);$("previewBtn").addEventListener("click",buildBrochure);$("printBtn").addEventListener("click",()=>window.print());$("printTopBtn").addEventListener("click",()=>window.print());buildBrochure()});
